version: "3.9"
services:
  ecommerce:
    container_name: ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ecommerce_db
      - DB_PORT=5432

  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ecommerce_db'
  